name: new-project

on: 
 push:
  branches:
   - main

jobs:
 terraform:
   runs-on: ubuntu-latest

   env: 
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

   steps:

    - name: code-checkout
      uses: actions/checkout@v4

    - name: setup  terraform
      uses: hashicorp/setup-terraform@v3

    - name: initaiate terraform
      run: terraform init

    - name: terraform format
      run: terraform fmt

    - name: terraform validate
      run: terraform validate

    - name: terraform apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve