name: new-project

on: 
 push:
  branches:
   - main

jobs:
 terraform:
   runs-on: ubuntu-latest

   env: 
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

   steps:

    - name: code-checkout
      uses: actions/checkout@v4

    - name: setup  terraform
      uses: harshicorp/setup-terraform@v3

    - name: initaiate terraform
      uses: terraform init

    - name: terraform format
      uses: terraform fmt

    - name: terraform validate
      uses: terraform validate

    - name: terraform apply
      uses: terraform apply -auto-approve